/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grasp;

import grasp.panels.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;

/**
 *
 * @author L55-C5211R
 */
public class GraspInterfaz extends javax.swing.JFrame {

    private int orden;
    private final GridBagLayout layout;
    private final GridBagConstraints c;
    private final PanelIntro pi;
    private final PanelConstruccion pConst;
    private final PanelMejora pMejora;
    public final static int CAPACIDADMOCHILAKG = 15;
    private final ArrayList<Cosas> cosas = new ArrayList<>();

    /**
     * Creates new form GraspInterfaz
     *
     */
    public GraspInterfaz() {
        initComponents();
        orden = 1;
        layout = new GridBagLayout();
        pnlDinamico.setLayout(layout);
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;

        
        cosas.add(new Cosas("Brujula", 2.0, 5.0));
        cosas.add(new Cosas("Tienda", 9.0, 7.0));
        cosas.add(new Cosas("Cantimplora con agua", 3.0, 25.0));
        cosas.add(new Cosas("Botiquin", 1.0, .5));
        cosas.add(new Cosas("Cuerda", 2.0, 10.0));
        cosas.add(new Cosas("Lampara", 1.0, 7.0));
        cosas.add(new Cosas("Cuchillo", .5, 5.0));
        cosas.add(new Cosas("Alimentos", 5.0, 1.0));
        cosas.add(new Cosas("Sleeping", 1.5, 10.0));
        

        pi = new PanelIntro(cosas);
        pConst = new PanelConstruccion(cosas);
        pMejora = new PanelMejora(cosas, pConst.getSolucionParcial());
        pnlDinamico.add(pi, c);
        pnlDinamico.add(pConst, c);
        pnlDinamico.add(pMejora, c);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSiguiente = new javax.swing.JButton();
        pnlDinamico = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(0, 0));

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        pnlDinamico.setMinimumSize(new java.awt.Dimension(640, 400));
        pnlDinamico.setPreferredSize(new java.awt.Dimension(640, 400));

        javax.swing.GroupLayout pnlDinamicoLayout = new javax.swing.GroupLayout(pnlDinamico);
        pnlDinamico.setLayout(pnlDinamicoLayout);
        pnlDinamicoLayout.setHorizontalGroup(
            pnlDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDinamicoLayout.setVerticalGroup(
            pnlDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(559, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addComponent(pnlDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        if (orden == 1) {
            pi.setVisible(false);
            pConst.setVisible(true);
            pMejora.setVisible(false);
        }
        if (pConst.steps(orden)) {
            orden++;
        } else if (orden >= 6) {
            if (orden == 6) {
                pConst.setVisible(false);
                pMejora.setVisible(true);
                pi.setVisible(false);
            }
            if (pMejora.stepsContinue(orden)) {
                orden++;
            }
            if(orden == 9){
                dispose();
            }
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlDinamico;
    // End of variables declaration//GEN-END:variables
}
